In [4]:
import sys

In [7]:
import sys
print(sys.executable)

c:\Users\inesc\Downloads\ISCTE\Planapp\Planapp\.venv\Scripts\python.exe

In [8]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\inesc\appdata\roaming\python\python313\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\inesc\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.3.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\inesc\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\inesc\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\inesc\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.6.0)

In [11]:
import sys
!{sys.executable} -m pip install --upgrade pip
!{sys.executable} -m pip install nltk
import nltk
nltk.download('stopwords')

Requirement already satisfied: pip in c:\users\inesc\downloads\iscte\planapp\planapp\.venv\lib\site-packages (25.3)
Requirement already satisfied: nltk in c:\users\inesc\downloads\iscte\planapp\planapp\.venv\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\inesc\downloads\iscte\planapp\planapp\.venv\lib\site-packages (from nltk) (8.3.0)
Requirement already satisfied: joblib in c:\users\inesc\downloads\iscte\planapp\planapp\.venv\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\inesc\downloads\iscte\planapp\planapp\.venv\lib\site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in c:\users\inesc\downloads\iscte\planapp\planapp\.venv\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\inesc\downloads\iscte\planapp\planapp\.venv\lib\site-packages (from click->nltk) (0.4.6)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\inesc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [12]:
import sklearn

In [13]:
# --- Environment Setup for VS Code ---

import pandas as pd
import numpy as np
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk

# Download NLTK stopwords (only the first time)
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords_pt = stopwords.words('portuguese')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\inesc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

#Sprint 2

In [19]:
# carregar o dataset 

parquet_path = "../../data/bronze/cision_news_20251110.parquet"

sample = pd.read_parquet(parquet_path, engine="pyarrow")

sample.head()

,id,titulo,noticia,link,data_publicacao,tipo_meio,autores,valor_publicitario,guid,categoria
0,116477697,Isabel Ferreira reafirma compromisso com Braga...,A candidata à Presidência da Câmara Municipal ...,No link available,2025-04-03T00:00:00+00:00,Imprensa,sem autor,139.4,http://pt.cision.com/cp2013/clippingdetails.as...,None
1,116477659,Legislativas 25 - Júlia Rodrigues escolhida pa...,"A presidente da Câmara de Mirandela, Júlia Rod...",No link available,2025-04-03T00:00:00+00:00,Imprensa,"Fernando Pires, António Gonçalves Rodrigues",267.2,http://pt.cision.com/cp2013/clippingdetails.as...,None
2,116456100,Alargamento dos passeios na envolvente à Casa-...,"Arrancou na passada segunda-feira, o alargamen...",No link available,2025-04-02T00:00:00+00:00,Imprensa,sem autor,100.0,http://pt.cision.com/cp2013/clippingdetails.as...,None
3,116477524,Macedo de Cavaleiros - Câmara investiu dois mi...,A Câmara de Macedo de Cavaleiros investiu mais...,No link available,2025-04-03T00:00:00+00:00,Imprensa,Glória Lopes,180.1,http://pt.cision.com/cp2013/clippingdetails.as...,None
4,116477522,OPINIÃO - Clarificação,Obviamente que é imperativo que a atuação de q...,No link available,2025-04-03T00:00:00+00:00,Imprensa,Leite Mário José,133.6,http://pt.cision.com/cp2013/clippingdetails.as...,None

In [20]:
sample.head(10)

,id,titulo,noticia,link,data_publicacao,tipo_meio,autores,valor_publicitario,guid,categoria
0,116477697,Isabel Ferreira reafirma compromisso com Braga...,A candidata à Presidência da Câmara Municipal ...,No link available,2025-04-03T00:00:00+00:00,Imprensa,sem autor,139.4,http://pt.cision.com/cp2013/clippingdetails.as...,None
1,116477659,Legislativas 25 - Júlia Rodrigues escolhida pa...,"A presidente da Câmara de Mirandela, Júlia Rod...",No link available,2025-04-03T00:00:00+00:00,Imprensa,"Fernando Pires, António Gonçalves Rodrigues",267.2,http://pt.cision.com/cp2013/clippingdetails.as...,None
2,116456100,Alargamento dos passeios na envolvente à Casa-...,"Arrancou na passada segunda-feira, o alargamen...",No link available,2025-04-02T00:00:00+00:00,Imprensa,sem autor,100.0,http://pt.cision.com/cp2013/clippingdetails.as...,None
3,116477524,Macedo de Cavaleiros - Câmara investiu dois mi...,A Câmara de Macedo de Cavaleiros investiu mais...,No link available,2025-04-03T00:00:00+00:00,Imprensa,Glória Lopes,180.1,http://pt.cision.com/cp2013/clippingdetails.as...,None
4,116477522,OPINIÃO - Clarificação,Obviamente que é imperativo que a atuação de q...,No link available,2025-04-03T00:00:00+00:00,Imprensa,Leite Mário José,133.6,http://pt.cision.com/cp2013/clippingdetails.as...,None
5,116477197,O atraso na Variante das Palhagueiras é o refl...,Há mais de 20 anos que é reconhecido pelos tor...,No link available,2025-04-04T00:00:00+00:00,Imprensa,João Paulo Reis,279.1,http://pt.cision.com/cp2013/clippingdetails.as...,None
6,116455753,António Soares é o candidato do Bloco de Esque...,António Soares é o candidato do Bloco de Esque...,No link available,2025-03-30T00:00:00+00:00,Imprensa,sem autor,365.9,http://pt.cision.com/cp2013/clippingdetails.as...,None
7,116455708,Fernando Vale e Andreia Neto candidatos a depu...,Fernando Vale e Andreia Neto são a escolha da ...,No link available,2025-03-30T00:00:00+00:00,Imprensa,sem autor,108.1,http://pt.cision.com/cp2013/clippingdetails.as...,None
8,116476980,Região - Politécnico de Leiria aponta três cam...,Politécnico aponta três caminhos para o desenv...,No link available,2025-04-03T00:00:00+00:00,Imprensa,Elisabete Cruz,623.7,http://pt.cision.com/cp2013/clippingdetails.as...,None
9,116466403,José Luís Carneiro desvaloriza polémica em Bra...,Legislativas 2025\n\nO antigo candidato à lide...,https://ominho.pt/jose-luis-carneiro-desvalori...,2025-04-02T00:00:00+00:00,Internet,sem autor,7154.0,http://pt.cision.com/cp2013/clippingdetails.as...,None

In [21]:
print(sample.shape)
print(sample.columns)
display(sample.head())
display(sample.dtypes)
print(sample.isna().sum())
print("Duplicados por corpo de noticia:", sample.duplicated(subset=["noticia"]).sum()) #mas têm valores unitarios dif

(60645, 10)
Index(['id', 'titulo', 'noticia', 'link', 'data_publicacao', 'tipo_meio',
       'autores', 'valor_publicitario', 'guid', 'categoria'],
      dtype='object')

,id,titulo,noticia,link,data_publicacao,tipo_meio,autores,valor_publicitario,guid,categoria
0,116477697,Isabel Ferreira reafirma compromisso com Braga...,A candidata à Presidência da Câmara Municipal ...,No link available,2025-04-03T00:00:00+00:00,Imprensa,sem autor,139.4,http://pt.cision.com/cp2013/clippingdetails.as...,None
1,116477659,Legislativas 25 - Júlia Rodrigues escolhida pa...,"A presidente da Câmara de Mirandela, Júlia Rod...",No link available,2025-04-03T00:00:00+00:00,Imprensa,"Fernando Pires, António Gonçalves Rodrigues",267.2,http://pt.cision.com/cp2013/clippingdetails.as...,None
2,116456100,Alargamento dos passeios na envolvente à Casa-...,"Arrancou na passada segunda-feira, o alargamen...",No link available,2025-04-02T00:00:00+00:00,Imprensa,sem autor,100.0,http://pt.cision.com/cp2013/clippingdetails.as...,None
3,116477524,Macedo de Cavaleiros - Câmara investiu dois mi...,A Câmara de Macedo de Cavaleiros investiu mais...,No link available,2025-04-03T00:00:00+00:00,Imprensa,Glória Lopes,180.1,http://pt.cision.com/cp2013/clippingdetails.as...,None
4,116477522,OPINIÃO - Clarificação,Obviamente que é imperativo que a atuação de q...,No link available,2025-04-03T00:00:00+00:00,Imprensa,Leite Mário José,133.6,http://pt.cision.com/cp2013/clippingdetails.as...,None

id                     object
titulo                 object
noticia                object
link                   object
data_publicacao        object
tipo_meio              object
autores                object
valor_publicitario    float64
guid                   object
categoria              object
dtype: object

id                        0
titulo                    0
noticia                   0
link                      0
data_publicacao           0
tipo_meio                 0
autores                   0
valor_publicitario        0
guid                      0
categoria             60645
dtype: int64
Duplicados por corpo de noticia: 723

só a coluna "categoria" é que tem nulos

In [22]:
# Datas e valores numéricos
sample["data_publicacao"] = pd.to_datetime(sample["data_publicacao"], errors="coerce")
sample["valor_publicitario"] = pd.to_numeric(sample["valor_publicitario"], errors="coerce")

# Normalizar texto das colunas relevantes
def norm_txt(s):
    s = str(s).lower()
    s = re.sub(r"[\:\;\,\.\!\?\(\)\[\]\-\–\—\"\']", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

#vamos ver com o corpo da noticia
sample["noticia"] = sample["noticia"].map(norm_txt)

##TF-IDF (melhor opção de todas)

In [8]:
#4. Vetorização TF-IDF + matriz de similaridade
vectorizer = TfidfVectorizer(stop_words=list(stopwords_pt), ngram_range=(1,2), max_features=30000, min_df=3)
X = vectorizer.fit_transform(sample["noticia"])

# Similaridade (mais baixo aumenta grupos)
from sklearn.neighbors import NearestNeighbors
from scipy.sparse.csgraph import connected_components

k = 25           # começa com 25
threshold = 0.76 # o mesmo que já usavas

nbrs = NearestNeighbors(n_neighbors=k, metric="cosine", n_jobs=-1)
nbrs.fit(X)

# grafo de distâncias (esparso) -> similaridade
G = nbrs.kneighbors_graph(mode="distance").tocsr()
G.data = 1.0 - G.data
G.data[G.data < threshold] = 0.0
G.eliminate_zeros()

# grupos por componentes conexos (labels = grupo de cada linha)
B = G.copy(); B.data[:] = 1.0
n_comp, labels = connected_components(csgraph=B, directed=False, return_labels=True)

In [9]:
#5. Agrupamento por similaridade
sample = sample.reset_index(drop=True)
sample["grupo_id"] = pd.Series(labels).astype("Int64")

In [10]:
# para contagens
from collections import Counter

sizes = Counter(sample["grupo_id"].value_counts().tolist())
print("Distribuição de tamanhos de grupo:", sizes)
print("Grupos totais:", sample["grupo_id"].nunique())
print("Grupos com 1 notícia:", (sample["grupo_id"].value_counts()==1).sum())

Distribuição de tamanhos de grupo: Counter({1: 36107, 2: 4032, 3: 1041, 4: 513, 5: 268, 6: 170, 7: 100, 8: 97, 9: 70, 11: 47, 10: 47, 12: 33, 14: 31, 13: 27, 17: 22, 15: 22, 19: 17, 21: 12, 18: 11, 16: 11, 25: 9, 20: 8, 26: 5, 24: 5, 29: 4, 34: 3, 32: 3, 30: 3, 22: 3, 37: 2, 35: 2, 31: 2, 27: 2, 81: 1, 73: 1, 70: 1, 49: 1, 47: 1, 44: 1, 41: 1, 40: 1, 38: 1, 28: 1, 23: 1})
Grupos totais: 42740
Grupos com 1 notícia: 36107

In [15]:
# Tabela com número de notícias por grupo
contagem_por_grupo = (
    sample.groupby("grupo_id")
          .size()
          .reset_index(name="num_noticias")
)

# Lista com os ids dos grupos que têm exatamente x notícias p.e.
grupos_x = contagem_por_grupo.loc[
    contagem_por_grupo["num_noticias"] ==47,"grupo_id"
].tolist()

print("Grupos com x notícias:", grupos_x)
print("Total de grupos com x notícias:", len(grupos_x))

Grupos com x notícias: [17699]
Total de grupos com x notícias: 1

In [16]:
#6. Escolher o líder por valor publicitário

def lider_valor_publicitario(df, grupo, col_valor="valor_publicitario"):
    # apenas retorna o índice da notícia com maior valor_publicitario dentro do grupo
    idx_validos = [int(i) for i in grupo if 0 <= int(i) < len(df)]
    return int(df.loc[idx_validos, col_valor].idxmax())

leaders = (sample.groupby("grupo_id")["valor_publicitario"].idxmax().dropna().astype(int).tolist())
sample["is_lider"] = False
sample.loc[leaders, "is_lider"] = True

In [17]:
#dos 4 grupos que tem 15 noticias
gid = grupos_x[0] #0 é o 1 grupo, 1 o segundo e etc
exemplo_4 = sample.loc[sample["grupo_id"] == gid, ["grupo_id","is_lider","noticia","data_publicacao", "valor_publicitario"]].head(50)
display(exemplo_4)

,grupo_id,is_lider,noticia,data_publicacao,valor_publicitario
24108,17699,False,ministro da educação fernando alexandre falou ...,2025-09-06 00:00:00+00:00,34795.20
24322,17699,False,o reitor da universidade do porto u porto antó...,2025-09-06 00:00:00+00:00,1307.44
24333,17699,True,reitor da universidade do porto denunciou ter ...,2025-09-06 00:00:00+00:00,48181.25
24338,17699,False,o ministro da educação ciência e inovação diss...,2025-09-06 00:00:00+00:00,9428.44
24340,17699,False,o reitor da universidade do porto u porto antó...,2025-09-06 00:00:00+00:00,15636.52
25970,17699,False,fernando alexandre diz que ainda não falou com...,2025-09-06 00:00:00+00:00,29355.52
25994,17699,False,o ministro da educação ciência e inovação diss...,2025-09-06 00:00:00+00:00,21583.91
26020,17699,False,“não ainda não falei com o reitor da u porto e...,2025-09-06 00:00:00+00:00,1500.00
26022,17699,False,o ministro da educação ciência e inovação diss...,2025-09-06 00:00:00+00:00,34065.94
26023,17699,False,o ministro da educação ciência e inovação diss...,2025-09-06 00:00:00+00:00,28443.46
26024,17699,False,o ministro da educação ciência e inovação diss...,2025-09-06 00:00:00+00:00,28443.46
26112,17699,False,antónio sousa pereira disse que a notícia avan...,2025-09-05 00:00:00+00:00,6071.14
26117,17699,False,o reitor da universidade do porto reiterou hoj...,2025-09-05 00:00:00+00:00,6071.14
26124,17699,False,o reitor da universidade do porto reiterou est...,2025-09-05 00:00:00+00:00,1428.10
26141,17699,False,filipe amorim / lusa o ministro da educação ci...,2025-09-05 00:00:00+00:00,1250.00
26219,17699,False,david pereira trinta candidatos que não tinham...,2025-09-06 00:00:00+00:00,17676.37
26257,17699,False,o reitor é eleito pelos seus pares presta cont...,2025-09-07 00:00:00+00:00,6274.24
26314,17699,False,o partido socialista pediu um audição quer do ...,2025-09-07 00:00:00+00:00,249.88
26341,17699,False,partido socialista pediu um audição quer do re...,2025-09-07 00:00:00+00:00,48181.25
26345,17699,False,até o senado académico o órgão de consulta que...,2025-09-06 00:00:00+00:00,103.00
26403,17699,False,há algo que eu queria lembrar ao ministro da e...,2025-09-07 00:00:00+00:00,29355.52
26481,17699,False,secretário geral do ps lembra que os reitores ...,2025-09-07 00:00:00+00:00,15636.52
26526,17699,False,o líder do ps avisou este domingo o ministro d...,2025-09-07 00:00:00+00:00,9428.44
26527,17699,False,o reitor não apresenta a demissão a um ministr...,2025-09-07 00:00:00+00:00,15187.72
26529,17699,False,“há algo que eu queria lembrar ao ministro da ...,2025-09-07 00:00:00+00:00,1500.00
26533,17699,False,o líder do ps avisou este domingo o ministro d...,2025-09-07 00:00:00+00:00,34065.94
26539,17699,False,o líder do ps avisou hoje o ministro da educaç...,2025-09-07 00:00:00+00:00,28443.46
26593,17699,False,7 setembro 2025 o ministro da educação ciência...,2025-09-07 00:00:00+00:00,104.44
32031,17699,False,a fap e as associações de estudantes da u port...,2025-09-06 00:00:00+00:00,249.88
32037,17699,False,o senado académico é um órgão de consulta que ...,2025-09-06 00:00:00+00:00,6274.24
32038,17699,False,o senado académico é um órgão de consulta que ...,2025-09-06 00:00:00+00:00,4443.23
32137,17699,False,o senado académico é um órgão de consulta que ...,2025-09-06 00:00:00+00:00,6274.24
32140,17699,False,a federação académica do porto fap e as associ...,2025-09-06 00:00:00+00:00,1428.10
32220,17699,False,os estudantes da academia do porto querem que ...,2025-09-06 00:00:00+00:00,17242.54
32296,17699,False,a federação académica do porto e as associaçõe...,2025-09-06 00:00:00+00:00,29355.52
32316,17699,False,a federação académica do porto fap e a associa...,2025-09-06 00:00:00+00:00,34065.94
34163,17699,False,a federação académica do porto fap e a associa...,2025-09-06 00:00:00+00:00,9428.44
34164,17699,False,os estudante da academia do porto querem que s...,2025-09-06 00:00:00+00:00,15636.52
34167,17699,False,os estudantes pedem um esclarecimento “perante...,2025-09-06 00:00:00+00:00,15187.72
34218,17699,False,estudante da academia do porto querem que se e...,2025-09-06 00:00:00+00:00,48181.25
34240,17699,False,a fap reitera o pedido de abertura de um inqué...,2025-09-06 00:00:00+00:00,4500.00
34313,17699,False,a federação académica do porto fap e a associa...,2025-09-06 00:00:00+00:00,28443.46
34323,17699,False,porto 06 set 2025 lusa a federação académica d...,2025-09-06 00:00:00+00:00,1500.00
34421,17699,False,federação académica do porto e associações de ...,2025-09-06 00:00:00+00:00,620.00
34431,17699,False,os estudante da academia do porto querem que s...,2025-09-06 00:00:00+00:00,130.06
43768,17699,False,a federação académica do porto fap e a associa...,2025-09-06 00:00:00+00:00,21583.91
43867,17699,False,a federação académica do porto fap e a associa...,2025-09-06 00:00:00+00:00,28443.46

In [18]:
ver_carac = sample[sample["grupo_id"] == 391 ]

display(ver_carac[["is_lider", "noticia", "tipo_meio", "valor_publicitario"]])

,is_lider,noticia,tipo_meio,valor_publicitario
448,True,os produtores portugueses têm de se preparar p...,Internet,46003.0
613,False,sector do calçado português anuncia que não de...,Internet,10935.0

In [19]:
# Inspecionar um grupo grande
gid_ex = sample["grupo_id"].value_counts().idxmax()
display(sample[sample["grupo_id"] == gid_ex][["id", "is_lider", "noticia", "valor_publicitario"]].head(50))

,id,is_lider,noticia,valor_publicitario
85,116472699,False,plan il portugal s caretaker ad government wil...,100.0
1262,117171220,False,dams il a visit to mér tola alentejo by the mi...,637.6
2213,116592436,False,by michael bruxo michael bruxo@port portugalre...,336.2
2531,116527050,False,ps pips psd to post in presenting electoral pr...,772.0
4773,116905942,False,were facing a huge challenge here in portugal ...,750.0
6171,116716811,False,olháo il portugal s environment and energy min...,428.9
6266,116765324,False,te renewal of the citizen card can now be done...,127.6
6275,116764337,False,portugal is showing strong signs of economic r...,452.4
8106,116971746,False,18 000 undocumented immigrants not wanted in p...,750.0
9279,117048750,False,first 4 574 immigrants lold portugal will not ...,1414.2
9638,117300881,False,the portuguese government announced that it wi...,385.6
12003,116951369,False,the santa cruz book fair returns from april 22...,1282.5
12046,116950010,False,government o 59 000 new unless vat is reduced ...,1147.6
12068,116949524,False,raise ii portugals minister of presidency has ...,208.7
12818,117073701,False,the agency for integration migration and asylu...,440.8
12866,117116716,False,guimarães green capital leading by example gui...,2957.9
13312,117172095,False,portalegre il environmental ngos from the c7 c...,208.7
14435,117209505,False,almost 1 400 immigrants ask for help to leave ...,526.0
15354,117279448,False,natasha don@portugaresident com support il exp...,405.7
15368,117278956,False,health il the algarve s public health system i...,301.4
15450,117567489,False,aima rejects 33 000 requests more than 33 000 ...,150.8
15451,117567488,False,the minister of the presidency has said that t...,336.4
16754,117421780,False,joaquim miranda sarmento finance minister “if ...,1611.3
18025,117446776,False,the president of the agency for integration mi...,394.4
18026,117446770,False,te minister of foreign afairs paulo rangel has...,127.6
18069,117445413,False,1 bragança owl rescue te gnr rescued an injure...,498.8
19153,117542757,False,foreigners il more than 33 000 foreigners in p...,100.0
19742,117902783,False,project to restore oyster reefs the university...,440.8
20513,117655284,False,prime minister luís montenegro excessive ourea...,1275.1
21192,117961017,False,are the conditions right to build more and spe...,8814.5
21213,117959218,False,housing let s not waste time or resources deli...,871.8
21214,117958983,False,investment fiscal predictability and cutting r...,1485.2
21215,117958770,False,nesta galeria pode ficar a par dos principais ...,11801.1
21499,117978136,False,on the 1st of april in london iberian property...,3971.4
21529,117674753,False,the new portuguese government luís montenegro ...,429.2
23148,117764302,False,almost two years after golden visas ended for ...,1913.0
24152,118017330,False,a technological leap with significant benefits...,866.1
25857,117880887,False,esm il the european stability mechanism esm ha...,428.9
25859,117880671,False,by natasha donn natasha donn@portugalresident ...,394.1
25860,117880634,False,the government is “accompanying the price of p...,100.0
26130,118365285,True,presidente da fundação bial | chairman of the ...,39698.4
28303,118632481,False,immigrants being underutilised immigrant worke...,440.8
28332,118632459,False,financial support to replace gas appliances an...,440.8
28554,118108954,False,housing il 109 new homes to be built across th...,359.4
28995,118362256,False,data il the number of unemployed people regist...,208.7
29000,118362117,False,by natasha donn natasha donn@portugalresident ...,521.6
29182,118379689,False,major projects include pavilion 7 refurbishmen...,1954.0
29487,118367689,False,thousands of homes delivered to families ten t...,464.0
29488,118367682,False,1 madeira cruise surge the 2024/2025 cruise se...,452.4
33043,118227017,False,housing il demolitions have begun at the site ...,173.9